"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-06

This initial migration creates every table from the SQLAlchemy model
metadata directly (Base.metadata.create_all/drop_all) rather than hand
-written op.create_table calls for each of the ~15 tables. Every later
schema change should be a normal autogenerated migration; this one exists
only to establish the baseline schema and the alembic_version tracking row.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from app.db.base import Base  # noqa: E402
from app.models import *  # noqa: E402,F401,F403

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    from alembic import op

    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    from alembic import op

    Base.metadata.drop_all(bind=op.get_bind())
